#
# Makefile for sensor chip drivers.
#

CFLAGS_KERNEL := -fno-strict-aliasing

obj-$(CONFIG_THERMAL)		+= thermal_sys.o
obj-$(CONFIG_CPU_THERMAL)       += cpu_cooling.o
obj-$(CONFIG_SPEAR_THERMAL)		+= spear_thermal.o
obj-$(CONFIG_EXYNOS_THERMAL)		+= exynos_thermal.o
